apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: homework
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: homework
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: homework
automountServiceAccountToken: false
